version: "3.6"
services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: duosmium
      POSTGRES_PASSWORD: e1d9b2OJcEvuZNo2Jj0z1IEmi4w59C0sRd125iLvip5IoKuRLCaGClgh1SzVgyFe  # change, obviously
      POSTGRES_DB: duosmium_rails_production
  web:
    build: .
    links:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3005:3000"
    depends_on:
      - db